SELECT NEW_BOOK.AUTHOR_ID, A.AUTHOR_NAME, NEW_BOOK.CATEGORY, NEW_BOOK.TOTAL_SALES
FROM (
    SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.TOTAL_SALES_AMOUNT) AS TOTAL_SALES
    FROM (
        SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES_AMOUNT
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
        GROUP BY BOOK_ID
    ) AS S
    LEFT OUTER JOIN BOOK AS B
    ON S.BOOK_ID = B.BOOK_ID
    GROUP BY B.AUTHOR_ID, B.CATEGORY
) AS NEW_BOOK
LEFT OUTER JOIN AUTHOR A
ON NEW_BOOK.AUTHOR_ID = A.AUTHOR_ID
ORDER BY NEW_BOOK.AUTHOR_ID ASC, NEW_BOOK.CATEGORY DESC;