# SELECT ITEM_ID,ITEM_NAME,RARITY
# FROM ITEM_INFO AS II
# INNER JOIN ITEM_TREE AS IT
# USING (ITEM_ID)
# WHERE NOT EXISTS(
#     SELECT 1
#     FROM ITEM_TREE
#     WHERE PARENT_ITEM_ID = II.ITEM_ID
# )
# ORDER BY ITEM_ID DESC;

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY 
FROM ITEM_INFO AS II
LEFT OUTER JOIN ITEM_TREE AS IT
ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC;