SELECT B.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) AS A
INNER JOIN REST_INFO AS B
ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.MAX_FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC;