-- 코드를 입력하세요
SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_CD,CATEGORY,PRICE
FROM FOOD_PRODUCT
WHERE PRICE=(SELECT MAX(PRICE) FROM FOOD_PRODUCT LIMIT 1);






# SELECT PRODUCTID, PRODUCTNAME, PRODUCTCD, CATEGORY, PRICE FROM FOODPRODUCT
# WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT LIMIT 1);

# WITH A AS (
# SELECT MAX(PRICE) AS MAXPRICE FROM FOODPRODUCT LIMIT 1
# )

# SELECT PRODUCTID, PRODUCTNAME, PRODUCTCD, CATEGORY, PRICE FROM FOODPRODUCT, A
# WHERE PRICE = A.MAX_PRICE;