# SELECT AO.ANIMAL_ID,AO.NAME
# FROM ANIMAL_OUTS AS AO
# LEFT OUTER JOIN ANIMAL_INS AS AI
# USING (ANIMAL_ID)
# WHERE AI.ANIMAL_TYPE IS NULL;

select ANIMAL_ID, name
from ANIMAL_OUTS AO
where not exists (select 1 from ANIMAL_INS where animal_id = AO.animal_id);