WITH USERS_INFO_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT 
    YEAR(SALES_DATE) AS SALES_YEAR,
    MONTH(SALES_DATE) AS SALES_MONTH,
    COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(USER_ID) FROM USERS_INFO_2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS
WHERE EXISTS (
    SELECT 1 
    FROM USERS_INFO_2021 AS UI
    WHERE OS.USER_ID = UI.USER_ID
)
GROUP BY SALES_YEAR, SALES_MONTH
ORDER BY SALES_YEAR, SALES_MONTH;