SELECT PRODUCT_ID,PRODUCT_NAME,FOOD_PRODUCT_TABLE.PRICE*TOTAL_AMOUNT_TABLE.TOTAL_AMOUNT AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID,SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
    ) AS TOTAL_AMOUNT_TABLE
INNER JOIN FOOD_PRODUCT AS FOOD_PRODUCT_TABLE
USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;