-- 코드를 입력하세요
# SELECT FLAVOR 
# FROM (SELECT FH.SHIPMENT_ID, FH.FLAVOR, (FH.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER_SUM
# FROM FIRST_HALF AS FH
# INNER JOIN JULY AS J
# USING (SHIPMENT_ID, FLAVOR)) AS JOIN_TABLE
# ORDER BY JOIN_TABLE.TOTAL_ORDER_SUM DESC LIMIT 3;

SELECT FLAVOR
FROM (
SELECT SHIPMENT_ID,FLAVOR,SUM(TOTAL_ORDER) AS TOTAL_ORDER_SUM
FROM (
    SELECT * FROM FIRST_HALF
    UNION
    SELECT * FROM JULY
    ) AS UNION_TABLE
GROUP BY FLAVOR
) AS UNION_GROUP_TABLE

ORDER BY TOTAL_ORDER_SUM DESC LIMIT 3;