WITH FRONTEND AS (
    SELECT DISTINCT (D.ID)
    FROM SKILLCODES AS S
    INNER JOIN DEVELOPERS AS D
    ON S.CODE & D.SKILL_CODE = S.CODE
    WHERE S.CATEGORY = "Front End"
    ORDER BY D.ID
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT * 
    FROM FRONTEND
)
ORDER BY ID ASC;