SELECT USER_ID, NICKNAME, TOTAL_PRICE
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_PRICE >= 700000
    )AS UGB
INNER JOIN USED_GOODS_USER AS UGU
ON UGB.WRITER_ID = UGU.USER_ID
ORDER BY TOTAL_PRICE ASC;
