SELECT HE.EMP_NO, EMP_NAME,
 CASE 
    WHEN TOTAL_SCORE >= 96 THEN 'S'
    WHEN TOTAL_SCORE >= 90 THEN 'A'
    WHEN TOTAL_SCORE >= 80 THEN 'B'
    ELSE 'C'
 END AS GRADE,
 CASE 
    WHEN TOTAL_SCORE >= 96 THEN SAL * 0.2
    WHEN TOTAL_SCORE >= 90 THEN SAL * 0.15
    WHEN TOTAL_SCORE >= 80 THEN SAL * 0.1
    ELSE 0
  END AS BONUS
FROM HR_EMPLOYEES AS HE
INNER JOIN (
    SELECT AVG(SCORE) AS TOTAL_SCORE, HG.EMP_NO
    FROM HR_GRADE AS HG
    LEFT OUTER JOIN HR_EMPLOYEES AS HE
    ON HG.EMP_NO = HE.EMP_NO
    GROUP BY HG.EMP_NO
) AS TOTAL_SCORE_TABLE
ON HE.EMP_NO = TOTAL_SCORE_TABLE.EMP_NO
ORDER BY HE.EMP_NO;

