-- 부모 형질을 모두 포함해야한다.
SELECT ED1.ID, ED1.GENOTYPE, ED2.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA ED1 LEFT JOIN ECOLI_DATA ED2
ON ED1.PARENT_ID = ED2.ID
WHERE ED1.PARENT_ID IS NOT NULL
AND (ED1.GENOTYPE & ED2.GENOTYPE = ED2.GENOTYPE)
ORDER BY ED1.ID ASC;