SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_SIZE_OF_COLONY - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS ED
LEFT OUTER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS NED
ON YEAR(ED.DIFFERENTIATION_DATE) = NED.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;