SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = (
    SELECT MAX(FI2.LENGTH)
    FROM FISH_INFO AS FI2
    WHERE FI2.FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID ASC;
