# SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
# FROM FISH_INFO AS FI
# INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
# WHERE FI.LENGTH = (
#     SELECT MAX(FI2.LENGTH)
#     FROM FISH_INFO AS FI2
#     WHERE FI2.FISH_TYPE = FI.FISH_TYPE
# )
# ORDER BY FI.ID ASC;

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO INNER JOIN FISH_NAME_INFO USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (
SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
)
ORDER BY ID ASC;