
SELECT HG.SCORE, HE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS HE
INNER JOIN (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ) AS HG
ON HE.EMP_NO = HG.EMP_NO
ORDER BY HG.SCORE DESC LIMIT 1;



