SELECT A.CATEGORY, A.MAX_PRICE, PRODUCT_NAME
FROM(
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ) AS A
INNER JOIN FOOD_PRODUCT AS B
ON A.CATEGORY = B.CATEGORY
WHERE A.MAX_PRICE = B.PRICE
ORDER BY MAX_PRICE DESC;