SELECT COUNT(*) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM FISH_INFO AS FI
INNER JOIN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH,10)) >= 33
) AS AVG_TABLE
ON FI.FISH_TYPE = AVG_TABLE.FISH_TYPE
GROUP BY FI.FISH_TYPE
ORDER BY FI.FISH_TYPE ASC;