WITH CODES AS (
    SELECT
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS PYCODE,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS C_CODE,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FECODE
    FROM DUAL
)

SELECT CASE 
    WHEN (SKILL_CODE & FECODE) AND (SKILL_CODE & PYCODE) THEN 'A'
    WHEN SKILL_CODE & C_CODE THEN 'B'
    WHEN SKILL_CODE & FECODE THEN 'C'
END GRADE, ID, EMAIL
FROM DEVELOPERS, CODES
WHERE SKILL_CODE & (FECODE + C_CODE)
ORDER BY GRADE, ID;